- hosts: localhost
  name: The tasks for creating the dotfiles
  connection: local

  tasks:
    - name: Clone dotfiles repo
      ansible.builtin.git: # noqa: latest
        repo: "https://github.com/creativecomposer/dotfiles.git"
        dest: "{{ lookup('env', 'HOME') }}/dotfiles"
        recursive: true
        update: true
        accept_hostkey: true
        version: main
      tags:
        - dotfiles
        - stow

    - name: Rename default .bashrc file # This is needed because normally all systems have a .bashrc
      ansible.builtin.command: mv $HOME/.bashrc $HOME/.bashrc.org
      args:
        removes: $HOME/.bashrc
        creates: $HOME/.bashrc.org
      tags:
        - dotfiles
        - stow

    - name: Stow dotfiles
      ansible.builtin.shell: cd $HOME/dotfiles && ./install.sh
      args:
        creates: $HOME/.bashrc
      register: install_dotfiles
      tags:
        - dotfiles
        - stow
