- hosts: localhost
  connection: local

  handlers:
    - name: Install nvm
      include_tasks: nvm.yml

  tasks:
    - name: Install homebrew packages after doing stow
      community.general.homebrew:
        name:
          - direnv
          - ffmpeg
          - fzf
          - jq
          - lua-language-server
          - ripgrep # telescope.nvim uses this to list files.
          - tree
          - youtube-dl
        state: present

    - command: "true"
      notify: Install nvm
